### ISSUE TITLE
`fips` field in latimes-county-totals.csv missing leading zeros

### ISSUE THREAD

**Issue by meli-lewis** [datadesk/california-coronavirus-data#10]
Heya, I grabbed [this CSV](https://github.com/datadesk/california-coronavirus-data/blob/master/latimes-county-totals.csv) today and found the `fips` field missing leading zeros; I cruised the file's history and it looks like this started with https://github.com/datadesk/california-coronavirus-data/commit/860ffb93b83ce5f1a1bcbeabc2a2376e121b86cf, on 4/25.

FWIW, I don't see this in the other files I glanced at that also have a FIPS field, but I'll update issue if I do. I'd poke through the code to find where the data type changed, but I'm on deadline!

Thanks for this, and I hope y'all are well.

**Comment by palewire** [comment]
Good catch. I'll try to get this fixed for you later tonight when we do our nightly archive run. I probably just goofed and forgot to include `dtype={"fips": str}` in our notebooks somewhere.

**Comment by meli-lewis** [comment]
It’s not urgent! I already mapped them to FIPS codes from another dataset I have. Thanks!

**Comment by palewire** [comment]
This is fixed.
