### ISSUE TITLE
Error in latimes-state-totals.csv

### ISSUE THREAD

**Issue by Apeder** [datadesk/california-coronavirus-data#12]
2020-06-04 may have total confirmed cases and new confirmed cases switched? That row lists only 5195 new cases, so new confirmed cases is a very large negative number that's skewing my charts.  

Thanks,

Andrew

https://github.com/datadesk/california-coronavirus-data/blob/master/latimes-state-totals.csv

**Comment by justinharkey** [comment]
It looks like they entered the new daily amount instead of the total cumulative amount as you said. new_confirmed_cases appears to be generated based on the incorrect number so you get ~-11,000 cases. Strange that it's data from 2 months ago that was corrupted.

**Comment by Apeder** [comment]
Looks like the error was corrected. Thanks!
