### ISSUE TITLE
Loss of historical data on skilled nursing facilities?

### ISSUE THREAD

**Issue by chipx86** [datadesk/california-coronavirus-data#14]
The past few days, the `cdph-skilled-nursing-facilities.csv` dataset has contained information only for the current day, losing all historical data. Is this intentional, or is it just an error? I haven't been able to track the trends from this dataset due to this issue.

**Comment by palewire** [comment]
This is an error. I'll look to fix it. Thank you for pointing it out.

**Comment by palewire** [comment]
I believe I have fixed the bug. Let me know if I got it wrong.

**Comment by chipx86** [comment]
Thank you! Looks great to me 👍 

The timing on your fix is funny. I just wrote new code for my Butte County COVID-19 dashboard (https://bc19.live) to detect this situation (not just for these feeds but others I track) so that my own scripts would notice if a feed seemed to reset its start date and would gracefully append it to a previously-fetched version of the feed. 

I hadn't realized yet that you'd fixed it, and ran my code 2 full minutes after your push. Saw that my script "worked," felt pretty good about it, but then realized from my debug output that it never ran the appending steps. Realized you must have fixed it, and immediately ran to GitHub to say thank you 😃.

**Comment by palewire** [comment]
Glad to hear it. I've added you to our README examples.

**Comment by chipx86** [comment]
Thanks!

Sadly, it looks like this regressed. The feed only has today's information.

**Comment by palewire** [comment]
Hmm. I'll patch this.
