### ISSUE TITLE
Skilled nursing facilities feed has been down

### ISSUE THREAD

**Issue by chipx86** [datadesk/california-coronavirus-data#15]
Hi,

I noticed this feed's been down for about a week. I'm guessing that's due to the official SNF feed no longer providing daily CSV exports, leaving the only available data in the dashboard? Unless I missed a new location for those, anyway.

Given that situation, I've become adept at writing scrapers for Tableau dashboards. So if the above is just out of operation indefinitely due to the lack of CSV exports, let me know. I'll work on it from my end, and perhaps I can help restore the feeds for you from my end, give you an endpoint to consume.

**Comment by chipx86** [comment]
Ah nevermind, looks like they have a centralized dataset here: https://data.chhs.ca.gov/dataset/test-cdph-skilled-nursing-facilities-covid-19/resource/d4d68f74-9176-4969-9f07-1546d81db5a7

Which is good, because the Tableau dashboard  actually serves up the table data as PNGs on scroll.

**Comment by chipx86** [comment]
I'm guessing that's what you're using, and they just aren't updating it.

**Comment by palewire** [comment]
Yes. In the first months of the pandemic we pulled this "by hand" each day, but when the portal came on line we switched over to scraping that.

**Comment by chipx86** [comment]
I've reached out to the CDPH about their upstream data feed. They said they're looking into a fix now.

**Comment by chipx86** [comment]
Closing this since I've received verification from CDPH of a fix on their end and it seems to be fixed on this end.
