### ISSUE TITLE
Vaccination data outdated

### ISSUE THREAD

**Issue by sweetleon** [datadesk/california-coronavirus-data#17]
The vaccination file hasn’t been updated since February 10. This is very useful data so I’d love to see it kept current.

**Comment by palewire** [comment]
Thanks for flagging this. We've been collecting the data but our archival routine was failing to post the latest stuff here. The files have been updated and will update daily. https://github.com/datadesk/california-coronavirus-data/commit/93f9760d454886fe5dede5dc62381e3530b427dc

**Comment by sweetleon** [comment]
Thanks for fixing/updating this!

On a related note, is there any way to see how many of the vaccine doses were the 2nd/final dose?
