### ISSUE TITLE
Vaccination data outdated again

### ISSUE THREAD

**Issue by sweetleon** [datadesk/california-coronavirus-data#18]
Hasn't updated in a week (latest is Feb 25).

**Comment by palewire** [comment]
Are you not looking at this file?

https://github.com/datadesk/california-coronavirus-data/blob/master/cdph-vaccination-county-totals.csv
![Screenshot from 2021-03-02 10-45-43](https://user-images.githubusercontent.com/9993/109698692-85570f80-7b44-11eb-800d-58f0dcd73206.png)

**Comment by sweetleon** [comment]
Oops! Looks like there was a bug in my "[code](https://docs.google.com/spreadsheets/d/17ptfaeMxUKvT-FpvsAylpW0muwCYimD-0eXBPE_8yEM/edit#gid=914794514)" and it wasn't looking at the latest rows. Sorry.

**Comment by palewire** [comment]
No biggie.
