### ISSUE TITLE
Alameda County stats not updated since Apr 04 (9 days ago)

### ISSUE THREAD

**Issue by kjieldsen** [datadesk/california-coronavirus-data#21]
Alameda county stats in latimes-place-totals.csv have not changed since 2021-04-04 (9 days ago).
Perhaps an ETL glitch?

**Comment by maloym** [comment]
Checked a dozen zip codes in Alameda County and figures on county page match LAT numbers.  4/13/2021

**Comment by palewire** [comment]
Here's our source. https://covid-19.acgov.org/data
