### ISSUE TITLE
latimes-place-totals.csv has integers in string-typed columns of some rows.

### ISSUE THREAD

**Issue by reinholtz** [datadesk/california-coronavirus-data#26]
In latimes-place-totals.csv There are some ill-formed rows:
1. Several cases of "id" column containing an integer rather than a string
2. Several cases of "name" column containing an integer rather than a string
3. There are also cases of "population" column being empty but that's probably not an error, more likely missing data

**Comment by palewire** [comment]
I think you've spotted an inconsistency in how we've standardized the places across counties. I will mark both as string in the docs.
