### ISSUE TITLE
cdph-adult-and-senior-care-facilities.csv is no longer updating

### ISSUE THREAD

**Issue by chipx86** [datadesk/california-coronavirus-data#27]
Hi,

For the past couple months, the `cdph-adult-and-senior-care-facilities.csv` dataset has lacked any new data. Is there a scraping problem, or is the data being retired?

Thanks!

**Comment by palewire** [comment]
We've continued to pull and archive the PDFs that contain the data, but we haven't put in the time to crowbar the data out. It can still be done and we'll likely get to it at some point.

**Comment by chipx86** [comment]
Are the scripts responsible for the data extraction public? If so, I might be able to help with any updates.

**Comment by chipx86** [comment]
Looks like the CSV file got emptied out a few days ago.

**Comment by palewire** [comment]
I think I got this back up. Sorry for the outage.
