### ISSUE TITLE
Error in latimes-county-totals.csv for San Mateo on 2021-08-13

### ISSUE THREAD

**Issue by jonspring** [datadesk/california-coronavirus-data#28]
date,county,fips,confirmed_cases,deaths,new_confirmed_cases,new_deaths
2021-08-13,San Mateo,081,0,0,-46231,-592

Seems all data to date for San Mateo zeroed out for 2021-08-13 in commit cf492f46dc33172a2735e582249ae55156fc4407

**Comment by palewire** [comment]
I believe this error has been fixed. Thank you for flagging it.
