### ISSUE TITLE
Bay Area cities?

### ISSUE THREAD

**Issue by derekouyang** [datadesk/california-coronavirus-data#3]
Hi, as of 4/9/20, Santa Clara County is posting city case counts. Do you have an estimate of if/when your tool will start including Bay Area daily city counts?

**Comment by palewire** [comment]
We're logging them privately but that part of the database hasn't got slotted into this pipeline yet. Stay tuned. It'll be in here soon.

**Comment by palewire** [comment]
They're now in the repo. We just haven't mapped them yet.

**Comment by derekouyang** [comment]
Thanks. I see Santa Clara County has rows for last 3 days now, but no case data attached.

**Comment by palewire** [comment]
I'm pretty sure it's there. As are the coordinates now.

**Comment by palewire** [comment]
I think I got it. Try it now.
