### ISSUE TITLE
Place Totals x and y field names changed

### ISSUE THREAD

**Issue by jcz530** [datadesk/california-coronavirus-data#4]
In the first row of latimes-agency-totals.csv file, the field name for 'x' changed to 'lon' but y remains y.
The readme still refers to 'x' and 'y'. 

This feels like a mistake. It should probably be changed back to x and y or changed to lon and lat.

The file being referred to
[https://github.com/datadesk/california-coronavirus-data/blob/master/latimes-place-totals.csv](https://github.com/datadesk/california-coronavirus-data/blob/master/latimes-place-totals.csv)

**Comment by palewire** [comment]
that's fixed. typo on my part.
