### ISSUE TITLE
Is this going to be updated daily?

### ISSUE THREAD

**Issue by LucidObscurity** [datadesk/california-coronavirus-data#5]
I've noticed it's the end of 4/17 and no updates for 2 days. Is this repository being abandoned?

**Comment by palewire** [comment]
I just forgot to do it last night. I will remember tonight. Give me an hour.

**Comment by palewire** [comment]
Done

https://github.com/datadesk/california-coronavirus-data/commit/57e198910d42fa852c4b65f529e6eb27951bcf76
