### ISSUE TITLE
Possible data error in state hospitalization totals

### ISSUE THREAD

**Issue by sdmac** [datadesk/california-coronavirus-data#7]
The `confirmed_hospitalizations` column in the [cdph-state-totals.csv](http://github.com/datadesk/california-coronavirus-data/blob/master/cdph-state-totals.csv) seems to have a possible bad data entry, introduced in this commit [57e198](https://github.com/datadesk/california-coronavirus-data/commit/57e198910d42fa852c4b65f529e6eb27951bcf76#diff-37d7ec78f5e1a53a114afab672878164).

Specifically, for `2020-04-17`, the `confirmed_hospitalizations` is `2180`, whereas for the previous day `2020-04-16` the total was `3141`, and the following day for `2020-04-18` is `3221`.

Is this a typo, and instead of `2180` should it be `3180`, which would make much more sense and not a large deviation from the previous and subsequent totals?

**Comment by palewire** [comment]
You are correct. This must have been a typo on our part. I am fixing it. Thank you.

**Comment by palewire** [comment]
Patch is here https://github.com/datadesk/california-coronavirus-data/commit/13ce350e8b5cb1601720e0b67280656414d03989
